config/routes.rb
Rails.application.routes.draw do
  resources :i_inspecaos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  delete '/delete_file:id', to: 'i_inspecaos#destroy_file', as: 'destroy_file'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/i_inspecao.rb
class IInspecao < ApplicationRecord
    has_one_attached :i_inspecao_anexo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/i_inspecaos_controller.rb
class IInspecaosController < ApplicationController
  before_action :set_i_inspecao, only: %i[ show edit update destroy ]

  # GET /i_inspecaos or /i_inspecaos.json
  def index
    @i_inspecaos = IInspecao.all
  end

  # GET /i_inspecaos/1 or /i_inspecaos/1.json
  def show
  end

  # GET /i_inspecaos/new
  def new
    @i_inspecao = IInspecao.new
  end

  # GET /i_inspecaos/1/edit
  def edit
  end

  # POST /i_inspecaos or /i_inspecaos.json
  def create
    @i_inspecao = IInspecao.new(i_inspecao_params)

    respond_to do |format|
      if @i_inspecao.save
        format.html { redirect_to i_inspecao_url(@i_inspecao), notice: "I inspecao was successfully created." }
        format.json { render :show, status: :created, location: @i_inspecao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @i_inspecao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /i_inspecaos/1 or /i_inspecaos/1.json
  def update
    respond_to do |format|
      if @i_inspecao.update(i_inspecao_params)
        format.html { redirect_to i_inspecao_url(@i_inspecao), notice: "I inspecao was successfully updated." }
        format.json { render :show, status: :ok, location: @i_inspecao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @i_inspecao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /i_inspecaos/1 or /i_inspecaos/1.json
  def destroy
    @i_inspecao.destroy!

    respond_to do |format|
      format.html { redirect_to i_inspecaos_url, notice: "I inspecao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def destroy_file
    file = ActiveStorage::Attachment.find(params[:id])
    file.purge
    respond_to do |format|
        format.html { redirect_to i_inspecao_url(@i_inspecao), notice: "I inspecao was successfully created." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_i_inspecao
      @i_inspecao = IInspecao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def i_inspecao_params
      params.require(:i_inspecao).permit(:nome, :descricao, :tipo, :status, :i_inspecao_anexo, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/i_inspecaos_helper.rb
module IInspecaosHelper
end

app/views/i_inspecaos/_form.html.erb
<%= simple_form_for(@i_inspecao) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :descricao %>
    <%= f.input :tipo %>
    <%= f.input :status %>
    <% if @i_inspecao.send('i_inspecao_anexo').attached? %>
    <%= link_to 'Deletar Arquivo', '#', id: 'delete-file', data: { file_id: @i_inspecao.send('i_inspecao_anexo').blob_id }, class: 'btn btn-danger' %>
    <% else %>
      <%= f.input :i_inspecao_anexo, label: 'Anexo de Inspeção' %>
    <% end %>
  </div>
  <br><br>
  <script>
  // JavaScript para deletar arquivo via AJAX
document.addEventListener('DOMContentLoaded', function() {
  const deleteButton = document.getElementById('delete-file');

  if (deleteButton) {
    deleteButton.addEventListener('click', function(event) {
      event.preventDefault();
      const fileId = deleteButton.dataset.file_id;

      if (confirm('Tem certeza que deseja deletar este arquivo?')) {
        // Requisição AJAX para deletar o arquivo
        fetch(`/delete_file/${fileId}`, {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
          }
        })
        .then(response => {
          if (response.ok) {
            // Arquivo deletado com sucesso
            console.log('Arquivo deletado com sucesso');
            // Aqui você pode adicionar código para atualizar a interface após a exclusão, se necessário
          } else {
            // Tratar erro
            console.error('Erro ao deletar arquivo');
          }
        })
        .catch(error => {
          console.error('Erro na requisição AJAX:', error);
        });
      }
    });
  }
});

  </script>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-success' %>
  </div>
<% end %>

app/views/i_inspecaos/_i_inspecao.html.erb
<div id="<%= dom_id i_inspecao %>">
  <p>
    <strong>Nome:</strong>
    <%= i_inspecao.nome %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= i_inspecao.descricao %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= i_inspecao.tipo %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= i_inspecao.status %>
  </p>

</div>

app/views/i_inspecaos/_modal_delete.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Remover
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Tem certeza?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button class="btn btn-danger"<%= @i_inspecao.i_inspecao_anexo.purge %>>Remover</button>
        
        
      </div>
    </div>
  </div>
</div>

app/views/i_inspecaos/edit.html.erb
<h1>Editing i inspecao</h1>

<%= render "form", i_inspecao: @i_inspecao %>

<br>

<div>
  <%= link_to "Show this i inspecao", @i_inspecao %> |
  <%= link_to "Back to i inspecaos", i_inspecaos_path %>
</div>

app/views/i_inspecaos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>I inspecaos</h1>

<div id="i_inspecaos">
  <% @i_inspecaos.each do |i_inspecao| %>
    <%= render i_inspecao %>
    <p>
      <%= link_to "Show this i inspecao", i_inspecao %>
    </p>
  <% end %>
</div>

<%= link_to "New i inspecao", new_i_inspecao_path %>

app/views/i_inspecaos/new.html.erb
<h1>New i inspecao</h1>

<%= render "form", i_inspecao: @i_inspecao %>

<br>

<div>
  <%= link_to "Back to i inspecaos", i_inspecaos_path %>
</div>

app/views/i_inspecaos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @i_inspecao %>

<div>
  <%= link_to "Edit this i inspecao", edit_i_inspecao_path(@i_inspecao) %> |
  <%= link_to "Back to i inspecaos", i_inspecaos_path %>

  <%= button_to "Destroy this i inspecao", @i_inspecao, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anexo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>